Repository veracruz-project/veracruz, pull requests merged in 2020-10, with the labels that each got.

#1 Fixed various minor snags missed in open-sourcing
  .clang-format
  README.markdown
  chihuahua/chihuahua.iml
Labels: bug, documentation

#17 Added templates for new issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#15 Bringing the repository in line with Github idioms
  CONTRIBUTING.markdown
  README.markdown
  SECURITY_DISCLOSURE.markdown
Labels: documentation

#18 Fix for anchor links in README
  README.markdown
Labels: bug, documentation

#20 Added Basma to the Authors list
  AUTHORS.markdown
Labels: documentation, repository
