Repository veracruz-project/veracruz, pull requests merged in 2020-11, with the labels that each got.

#25 Change the README so that it's less intimidating for newcomers
  README.markdown
Labels: documentation, enhancement, repository

#34 CI script for AWS CodeBuild.
  Makefile
  buildspec.yml
Labels: build-process, enhancement, repository

#31 Added AWS CI build badge to README
  README.markdown
Labels: build-process, documentation, enhancement, repository

#39 Changed badge branch from `master` to `main`
  README.markdown
Labels: bug, build-process, documentation, repository

#40 futures-fix: added compiler pragma to test source files
  durango/src/lib.rs
  veracruz-test/src/main.rs
Labels: bug, build-process

#32 Make instructions consistent with current structure
  BUILD_INSTRUCTIONS.markdown
Labels: bug, build-process, documentation, enhancement

#38 Added Rustdoc support for SDK
  chihuahua/src/hcall/common.rs
  chihuahua/src/hcall/wasmi.rs
  chihuahua/src/hcall/wasmtime.rs
  sdk/Makefile
  sdk/examples/idash2017-logistic-regression/Makefile
  sdk/examples/idash2017-logistic-regression/src/main.rs
  sdk/examples/intersection-set-sum/Makefile
  sdk/examples/intersection-set-sum/src/main.rs
  sdk/examples/linear-regression/Makefile
  sdk/examples/linear-regression/src/main.rs
  sdk/examples/logistic-regression/Makefile
  sdk/examples/moving-average-convergence-divergence/Makefile
  sdk/examples/moving-average-convergence-divergence/src/main.rs
  sdk/examples/nop/Makefile
  sdk/examples/nop/src/main.rs
  sdk/examples/private-set-intersection-sum/Makefile
  sdk/examples/private-set-intersection-sum/src/main.rs
  sdk/examples/private-set-intersection/Makefile
  sdk/examples/private-set-intersection/src/main.rs
  sdk/examples/random-source/Makefile
  sdk/examples/random-source/src/main.rs
  sdk/examples/string-edit-distance/Makefile
  sdk/examples/string-edit-distance/src/main.rs
  sdk/freestanding-chihuahua/Makefile
  sdk/libveracruz/Makefile
  sdk/libveracruz/src/data_description.rs
  sdk/veracruz-rt/Makefile
Labels: build-process, documentation, sdk

#43 Handle unhandled error related to execution strategy selection in Mexico City
  mexico-city/src/managers/baja_manager.rs
  mexico-city/src/managers/error.rs
  mexico-city/src/managers/mod.rs
Labels: bug, trusted-veracruz-runtime

#45 Batch processing extension
  TEST_PLAN.markdown
  chihuahua/Cargo.toml
  chihuahua/src/error/common.rs
  chihuahua/src/factory.rs
  chihuahua/src/hcall/common.rs
  chihuahua/src/hcall/wasmi.rs
  chihuahua/src/hcall/wasmtime.rs
  colima/protos/colima.proto
  colima/src/custom.rs
  mexico-city/src/managers/buffer.rs
  mexico-city/src/managers/chihuahua_manager.rs
  mexico-city/src/managers/error.rs
  mexico-city/src/managers/mod.rs
  run_sinaloa_test_tz.sh
  sdk/Makefile
  sdk/data-generators/number-stream-generator/Cargo.toml
  sdk/data-generators/number-stream-generator/Makefile
  sdk/data-generators/number-stream-generator/src/main.rs
  sdk/freestanding-chihuahua/src/main.rs
  sdk/rust-language-support/examples/number-stream-accumulation/Cargo.toml
  sdk/rust-language-support/examples/number-stream-accumulation/Makefile
  sdk/rust-language-support/examples/number-stream-accumulation/Xargo.toml
  sdk/rust-language-support/examples/number-stream-accumulation/src/main.rs
  sdk/rust-language-support/libveracruz/src/host.rs
  sdk/tlaxcala/Makefile
  sdk/tlaxcala/tlaxcala_config.json
  sinaloa-test/src/main.rs
  test-collateral/Makefile
  test-collateral/generate_policy.py
  test-collateral/policy.template
  veracruz-utils/src/policy.rs
Labels: enhancement, sdk, trusted-veracruz-runtime
