Repository veracruz-project/veracruz, pull requests merged in 2021-11, with the labels that each got.

#248 Splitting veracruz-utils into smaller more focussed libraries
  execution-engine/Cargo.toml
  execution-engine/src/fs.rs
  execution-engine/src/lib.rs
  execution-engine/src/wasi/common.rs
  execution-engine/src/wasi/wasmi.rs
  execution-engine/src/wasi/wasmtime.rs
  io-utils/Cargo.toml
  io-utils/src/error.rs
  io-utils/src/lib.rs
  io-utils/src/nitro.rs
  io-utils/src/raw_fd.rs
  io-utils/src/vsocket.rs
  policy-utils/Cargo.toml
  policy-utils/src/error.rs
  policy-utils/src/expiry.rs
  policy-utils/src/lib.rs
  policy-utils/src/parsers.rs
  policy-utils/src/policy.rs
  policy-utils/src/principal.rs
  runtime-manager/Cargo.toml
  runtime-manager/src/managers/error.rs
  runtime-manager/src/managers/execution_engine_manager.rs
  runtime-manager/src/managers/mod.rs
  runtime-manager/src/managers/session_manager.rs
  runtime-manager/src/runtime_manager_nitro.rs
  sdk/freestanding-execution-engine/Cargo.toml
  sdk/freestanding-execution-engine/src/main.rs
  session-manager/Cargo.toml
  session-manager/src/session.rs
  session-manager/src/session_context.rs
  test-collateral/generate-policy/Cargo.toml
  test-collateral/generate-policy/src/main.rs
  veracruz-client/Cargo.toml
  veracruz-client/src/attestation.rs
  veracruz-client/src/cli.rs
  veracruz-client/src/error.rs
  veracruz-client/src/tests.rs
  veracruz-client/src/veracruz_client.rs
  veracruz-server-test/Cargo.toml
  veracruz-server-test/src/main.rs
  veracruz-server/Cargo.toml
  veracruz-server/fuzz/fuzz_targets/init_veracruz_server.rs
  veracruz-server/fuzz/fuzz_targets/provision_data.rs
  veracruz-server/src/cli.rs
  veracruz-server/src/server.rs
  veracruz-server/src/veracruz_server.rs
  veracruz-server/src/veracruz_server_icecap.rs
  veracruz-server/src/veracruz_server_nitro.rs
  veracruz-server/src/veracruz_server_sgx.rs
  veracruz-server/src/veracruz_server_tz.rs
  veracruz-test/Cargo.toml
  veracruz-test/src/main.rs
  veracruz-utils/Cargo.toml
  veracruz-utils/src/lib.rs
  veracruz-utils/src/platform/mod.rs
  veracruz-utils/src/platform/nitro/mod.rs
  veracruz-utils/src/platform/nitro/nitro.rs
  veracruz-utils/src/platform/tz/mod.rs
  veracruz-utils/src/policy/mod.rs
Labels: trusted-veracruz-runtime, always-refactoring

#116 Ported Veracruz to Linux
  .github/workflows/main.yml
  Makefile
  io-utils/Cargo.toml
  io-utils/src/error.rs
  io-utils/src/fd.rs
  io-utils/src/http.rs
  io-utils/src/lib.rs
  io-utils/src/tcp.rs
  linux-root-enclave/Cargo.toml
  linux-root-enclave/Makefile
  linux-root-enclave/src/main.rs
  platform-services/Cargo.toml
  platform-services/src/sgx_platform_services.rs
  policy-utils/src/lib.rs
  policy-utils/src/policy.rs
  proxy-attestation-server/Cargo.toml
  proxy-attestation-server/build-proxy-attestation-server-optee.sh
  proxy-attestation-server/src/attestation.rs
  proxy-attestation-server/src/attestation/nitro.rs
  proxy-attestation-server/src/attestation/psa.rs
  proxy-attestation-server/src/server.rs
  proxy-attestation-server/src/test.rs
  psa-attestation/Cargo.toml
  psa-attestation/build.rs
  runtime-manager/Cargo.toml
  runtime-manager/Makefile
  runtime-manager/src/main.rs
  runtime-manager/src/managers/error.rs
  runtime-manager/src/managers/execution_engine_manager.rs
  runtime-manager/src/managers/mod.rs
  runtime-manager/src/runtime_manager.rs
  runtime-manager/src/runtime_manager_linux.rs
  runtime-manager/src/runtime_manager_nitro.rs
  sdk/freestanding-execution-engine/Cargo.toml
  test-collateral/Makefile
  test-collateral/generate-policy/Cargo.toml
  test-collateral/generate-policy/src/main.rs
  veracruz-client/Cargo.toml
  veracruz-client/src/veracruz_client.rs
  veracruz-server-test/Cargo.toml
  veracruz-server-test/src/main.rs
  veracruz-server/Cargo.toml
  veracruz-server/Makefile
  veracruz-server/src/lib.rs
  veracruz-server/src/server.rs
  veracruz-server/src/veracruz_server.rs
  veracruz-server/src/veracruz_server_icecap.rs
  veracruz-server/src/veracruz_server_linux.rs
  veracruz-server/src/veracruz_server_nitro.rs
  veracruz-server/src/veracruz_server_sgx.rs
  veracruz-server/src/veracruz_server_tz.rs
  veracruz-test/Cargo.toml
  veracruz-test/src/main.rs
  veracruz-utils/Cargo.toml
  veracruz-utils/src/lib.rs
  veracruz-utils/src/platform/linux.rs
  veracruz-utils/src/platform/mod.rs
  veracruz-utils/src/platform/nitro/nitro.rs
  veracruz-utils/src/platform/vm.rs
Labels: enhancement, trusted-veracruz-runtime, attestation, build-process

#255 githooks/pre-commit: Also check for trailing whitespace.
  githooks/pre-commit
Labels: enhancement, build-process

#256 Cargo Git configuration improvements
  .cargo/config
Labels: enhancement, build-process

#253 Normalized all Cargo/Xargo.toml files
  execution-engine/Cargo.toml
  icecap/src/rust/icecap-wrapper-dummy/Cargo.toml
  io-utils/Cargo.toml
  linux-root-enclave/Cargo.toml
  platform-services/Cargo.toml
  platform-services/Xargo.toml
  policy-utils/Cargo.toml
  proxy-attestation-server/Cargo.toml
  psa-attestation/Cargo.toml
  psa-attestation/Xargo.toml
  runtime-manager-bind/Cargo.toml
  runtime-manager/Cargo.toml
  runtime-manager/Xargo.toml
  sdk/data-generators/csv-encoder/Cargo.toml
  sdk/data-generators/idash2017-logistic-regression-generator/Cargo.toml
  sdk/data-generators/image-processing-generator/Cargo.toml
  sdk/data-generators/intersection-set-sum-generator/Cargo.toml
  sdk/data-generators/linear-regression-generator/Cargo.toml
  sdk/data-generators/moving-average-convergence-divergence-generator/Cargo.toml
  sdk/data-generators/number-stream-generator/Cargo.toml
  sdk/data-generators/private-set-intersection-generator/Cargo.toml
  sdk/data-generators/private-set-intersection-sum-generator/Cargo.toml
  sdk/data-generators/shamir-secret-sharing/Cargo.toml
  sdk/data-generators/string-generator/Cargo.toml
  sdk/freestanding-execution-engine/Cargo.toml
  sdk/rust-examples/audio-event-triangulation/Cargo.toml
  sdk/rust-examples/idash2017-logistic-regression/Cargo.toml
  sdk/rust-examples/image-processing/Cargo.toml
  sdk/rust-examples/intersection-set-sum/Cargo.toml
  sdk/rust-examples/linear-regression/Cargo.toml
  sdk/rust-examples/logistic-regression/Cargo.toml
  sdk/rust-examples/moving-average-convergence-divergence/Cargo.toml
  sdk/rust-examples/nop/Cargo.toml
  sdk/rust-examples/number-stream-accumulation/Cargo.toml
  sdk/rust-examples/private-set-intersection-sum/Cargo.toml
  sdk/rust-examples/private-set-intersection/Cargo.toml
  sdk/rust-examples/random-source/Cargo.toml
  sdk/rust-examples/read-file/Cargo.toml
  sdk/rust-examples/shamir-secret-sharing/Cargo.toml
  sdk/rust-examples/string-edit-distance/Cargo.toml
  session-manager/Cargo.toml
  session-manager/Xargo.toml
  sgx-root-enclave-bind/Cargo.toml
  sgx-root-enclave/Cargo.toml
  test-collateral/generate-policy/Cargo.toml
  transport-protocol/Cargo.toml
  trustzone-root-enclave/Cargo.toml
  trustzone-root-enclave/Xargo.toml
  veracruz-client/Cargo.toml
  veracruz-server-test/Cargo.toml
  veracruz-server/Cargo.toml
  veracruz-server/fuzz/Cargo.toml
  veracruz-test/Cargo.toml
  veracruz-utils/Cargo.toml
Labels: sdk, trusted-veracruz-runtime, client-code, build-process, testing, always-refactoring, server

#193 Directory support and separate file descriptor spaces in the execution engine.
  CLI_INSTRUCTIONS.markdown
  execution-engine/Cargo.toml
  execution-engine/README.markdown
  execution-engine/src/fs.rs
  execution-engine/src/lib.rs
  execution-engine/src/wasi/common.rs
  execution-engine/src/wasi/wasmi.rs
  execution-engine/src/wasi/wasmtime.rs
  policy-utils/src/error.rs
  policy-utils/src/parsers.rs
  policy-utils/src/policy.rs
  policy-utils/src/principal.rs
  runtime-manager/Cargo.toml
  runtime-manager/src/managers/execution_engine_manager.rs
  runtime-manager/src/managers/mod.rs
  sdk/data-generators/idash2017-logistic-regression-generator/src/main.rs
  sdk/data-generators/number-stream-generator/Makefile
  sdk/data-generators/number-stream-generator/src/main.rs
  sdk/data-generators/private-set-intersection-generator/src/main.rs
  sdk/data-generators/private-set-intersection-sum-generator/Makefile
  sdk/data-generators/private-set-intersection-sum-generator/src/main.rs
  sdk/data-generators/shamir-secret-sharing/src/main.rs
  sdk/freestanding-execution-engine/Cargo.toml
  sdk/freestanding-execution-engine/src/main.rs
  sdk/rust-examples/idash2017-logistic-regression/src/main.rs
  sdk/rust-examples/image-processing/src/main.rs
  sdk/rust-examples/intersection-set-sum/src/main.rs
  sdk/rust-examples/linear-regression/src/main.rs
  sdk/rust-examples/logistic-regression/src/main.rs
  sdk/rust-examples/moving-average-convergence-divergence/src/main.rs
  sdk/rust-examples/number-stream-accumulation/src/main.rs
  sdk/rust-examples/private-set-intersection-sum/src/main.rs
  sdk/rust-examples/private-set-intersection/src/main.rs
  sdk/rust-examples/random-source/src/main.rs
  sdk/rust-examples/read-file/src/main.rs
  sdk/rust-examples/shamir-secret-sharing/src/main.rs
  sdk/rust-examples/string-edit-distance/src/main.rs
  test-collateral/Makefile
  test-collateral/generate-policy/src/main.rs
  transport-protocol/protos/transport_protocol.proto
  transport-protocol/src/custom.rs
  veracruz-client/src/cli.rs
  veracruz-client/src/error.rs
  veracruz-client/src/tests.rs
  veracruz-client/src/veracruz_client.rs
  veracruz-server-test/src/main.rs
  veracruz-server/src/veracruz_server.rs
  veracruz-test/src/main.rs
Labels: enhancement, trusted-veracruz-runtime

#132 Added support for JITting with Wasmtime on Nitro
  execution-engine/src/lib.rs
Labels: enhancement, trusted-veracruz-runtime

#205 Remove Trustzone root enclave
  .github/workflows/main.yml
  Makefile
  proxy-attestation-server/src/attestation/psa.rs
  runtime-manager/Cargo.toml
  runtime-manager/src/runtime_manager.rs
  runtime-manager/src/runtime_manager_trustzone.rs
  test-collateral/generate-policy/Cargo.toml
  test-collateral/generate-policy/src/main.rs
  test-collateral/populate-test-database.sh
  trustzone-root-enclave/Makefile
  trustzone-root-enclave/build.rs
  trustzone-root-enclave/src/main.rs
  trustzone-root-enclave/ta_aarch64.lds
  trustzone-root-enclave/ta_arm.lds
  trustzone-root-enclave/ta_static.rs
  tz_env.sh
  veracruz-server-test/cp-veracruz-server-test-tz.sh
  veracruz-server/build.rs
  veracruz-server/src/veracruz_server_tz.rs
  veracruz-utils/src/platform/tz/mod.rs
  veracruz-utils/src/platform/tz/runtime_manager_opcode.rs
Labels: trusted-veracruz-runtime, attestation, always-refactoring

#263 githooks/pre-commit: Use perl to detect trailing whitespace.
  githooks/pre-commit
Labels: bug, repository, build-process

#266 Pin openssl-sys to 0.9.70
  io-utils/Cargo.toml
  linux-root-enclave/Cargo.toml
  proxy-attestation-server/Cargo.toml
  veracruz-client/Cargo.toml
  veracruz-server/Cargo.toml
Labels: bug

#264 Cleaned up some vestigal mentions of the TrustZone root enclave
  COMPONENTS.markdown
  proxy-attestation-server/get-enclave-hash.sh
  runtime-manager/src/runtime_manager_trustzone.rs
  trustzone-root-enclave-uuid.txt
  trustzone-root-enclave/Cargo.toml
  trustzone-root-enclave/Xargo.toml
  veracruz-utils/build.rs
  veracruz-utils/src/platform/tz/mod.rs
  veracruz-utils/src/platform/tz/root_enclave_opcode.rs
Labels: bug, trusted-veracruz-runtime, always-refactoring, server

#254 Ensure that SDK, and immediate dependencies, is Clippy-clean
  execution-engine/src/fs.rs
  execution-engine/src/wasi/common.rs
  execution-engine/src/wasi/wasmi.rs
  execution-engine/src/wasi/wasmtime.rs
  platform-services/src/lib.rs
  platform-services/src/std_platform_services.rs
  policy-utils/src/lib.rs
  policy-utils/src/parsers.rs
  policy-utils/src/policy.rs
  policy-utils/src/principal.rs
  sdk/data-generators/idash2017-logistic-regression-generator/src/main.rs
  sdk/data-generators/intersection-set-sum-generator/src/main.rs
  sdk/data-generators/moving-average-convergence-divergence-generator/src/main.rs
  sdk/data-generators/private-set-intersection-generator/src/main.rs
  sdk/data-generators/shamir-secret-sharing/src/main.rs
  sdk/freestanding-execution-engine/src/main.rs
  sdk/rust-examples/audio-event-triangulation/src/main.rs
  sdk/rust-examples/idash2017-logistic-regression/src/main.rs
  sdk/rust-examples/logistic-regression/src/main.rs
  sdk/rust-examples/moving-average-convergence-divergence/src/main.rs
  sdk/rust-examples/private-set-intersection/src/main.rs
  sdk/rust-examples/shamir-secret-sharing/src/main.rs
Labels: sdk, trusted-veracruz-runtime, always-refactoring

#265 Fix pgen
  test-collateral/generate-policy/src/main.rs
Labels: bug, sdk, testing

#258 Added Nitro build to CI workflow
  .github/workflows/main.yml
Labels: build-process, testing

#197 Add `make quick-clean` rule to clean everything but LLVM
  Makefile
  sdk/Makefile
Labels: enhancement, build-process

#271 Added the Veracruz project technical charter
  documents/veracruz-ccc-technical-charter.pdf
Labels: repository

#268 Remove redundant imports from project components
  execution-engine/Cargo.toml
  linux-root-enclave/Cargo.toml
  proxy-attestation-server/Cargo.toml
  runtime-manager/Cargo.toml
  sdk/data-generators/csv-encoder/Cargo.toml
  sdk/data-generators/idash2017-logistic-regression-generator/Cargo.toml
  sdk/data-generators/intersection-set-sum-generator/Cargo.toml
  sdk/data-generators/linear-regression-generator/Cargo.toml
  sdk/data-generators/moving-average-convergence-divergence-generator/Cargo.toml
  sdk/data-generators/number-stream-generator/Cargo.toml
  sdk/data-generators/private-set-intersection-sum-generator/Cargo.toml
  sdk/data-generators/string-generator/Cargo.toml
  sdk/freestanding-execution-engine/Cargo.toml
  sdk/rust-examples/moving-average-convergence-divergence/Cargo.toml
  sdk/rust-examples/number-stream-accumulation/Cargo.toml
  sdk/rust-examples/private-set-intersection-sum/Cargo.toml
  sdk/rust-examples/shamir-secret-sharing/Cargo.toml
  session-manager/Cargo.toml
  sgx-root-enclave/Cargo.toml
  test-collateral/generate-policy/Cargo.toml
  veracruz-client/Cargo.toml
  veracruz-server-test/Cargo.toml
  veracruz-server/Cargo.toml
  veracruz-test/Cargo.toml
  veracruz-utils/Cargo.toml
Labels: sdk, trusted-veracruz-runtime, client-code, attestation, build-process, testing, always-refactoring, server
