Repository veracruz-project/veracruz, pull requests merged in 2021-07, with the labels that each got.

#153 Add image processing example
  sdk/Makefile
  sdk/data-generators/image-processing-generator/Cargo.toml
  sdk/data-generators/image-processing-generator/Makefile
  sdk/data-generators/image-processing-generator/src/main.rs
  sdk/rust-examples/image-processing/Cargo.toml
  sdk/rust-examples/image-processing/Makefile
  sdk/rust-examples/image-processing/src/main.rs
Labels: enhancement, sdk, testing

#166 Minor project Makefile fixes
  Makefile
Labels: bug, build-process, testing

#162 Add shortform "r" and "w" capability names to pgen
  test-collateral/generate-policy/src/main.rs
Labels: always-refactoring, sdk, testing

#181 Fix type signature check of clock_time_get()
  execution-engine/src/wasi/wasmi.rs
Labels: bug, trusted-veracruz-runtime

#178 Recover the performance test.
  run_veracruz_server_test_tz.sh
  sdk/data-generators/idash2017-logistic-regression-generator/Makefile
  sdk/data-generators/moving-average-convergence-divergence-generator/Makefile
  sdk/data-generators/private-set-intersection-sum-generator/Makefile
  sdk/freestanding-execution-engine/Cargo.toml
  test-collateral/Makefile
  veracruz-server-test/src/main.rs
Labels: build-process, enhancement, testing
