Repository veracruz-project/veracruz, pull requests merged in 2021-04, with the labels that each got.

#113 Reorganization of content of veracruz-utils to make way for Linux support
  runtime-manager/build.rs
  runtime-manager/src/managers/error.rs
  runtime-manager/src/managers/execution_engine_manager.rs
  runtime-manager/src/managers/mod.rs
  runtime-manager/src/managers/session_manager.rs
  runtime-manager/src/runtime_manager_trustzone.rs
  session-manager/src/session.rs
  session-manager/src/session_context.rs
  trustzone-root-enclave/src/main.rs
  veracruz-client/src/attestation.rs
  veracruz-client/src/error.rs
  veracruz-client/src/tests.rs
  veracruz-client/src/veracruz_client.rs
  veracruz-server-test/src/main.rs
  veracruz-server/fuzz/fuzz_targets/init_veracruz_server.rs
  veracruz-server/fuzz/fuzz_targets/provision_data.rs
  veracruz-server/src/server.rs
  veracruz-server/src/veracruz_server.rs
  veracruz-server/src/veracruz_server_nitro.rs
  veracruz-server/src/veracruz_server_sgx.rs
  veracruz-server/src/veracruz_server_tz.rs
  veracruz-test/src/main.rs
  veracruz-utils/Cargo.toml
  veracruz-utils/src/io/error.rs
  veracruz-utils/src/io/mod.rs
  veracruz-utils/src/io/raw_fd.rs
  veracruz-utils/src/io/vsocket.rs
  veracruz-utils/src/lib.rs
  veracruz-utils/src/platform/mod.rs
  veracruz-utils/src/platform/nitro/mod.rs
  veracruz-utils/src/platform/nitro/nitro.rs
  veracruz-utils/src/platform/nitro/nitro_enclave.rs
  veracruz-utils/src/platform/tz/mod.rs
  veracruz-utils/src/platform/tz/root_enclave_opcode.rs
  veracruz-utils/src/platform/tz/runtime_manager_opcode.rs
  veracruz-utils/src/policy.rs
  veracruz-utils/src/policy/error.rs
  veracruz-utils/src/policy/expiry.rs
  veracruz-utils/src/policy/mod.rs
  veracruz-utils/src/policy/policy.rs
  veracruz-utils/src/policy/principal.rs
  veracruz-utils/src/runtime_manager_opcode.rs
  veracruz-utils/src/trustzone_root_enclave_opcode.rs
  veracruz-utils/src/vsocket.rs
Labels: always-refactoring, attestation, documentation, repository, trusted-veracruz-runtime

#125 Fix a dependency issue
  execution-engine/Cargo.toml
  sdk/freestanding-execution-engine/Cargo.toml
Labels: bug, build-process

#115 Added "std" feature for session-manager
  session-manager/Cargo.toml
Labels: enhancement, trusted-veracruz-runtime

#126 Fixed broken socket2 dependency
  nitro-root-enclave-server/Cargo.toml
  proxy-attestation-server/Cargo.toml
  veracruz-client/Cargo.toml
  veracruz-server-test/Cargo.toml
  veracruz-server/Cargo.toml
Labels: bug, build-process

#127 Updated README with CCC logo
  README.markdown
Labels: documentation, repository

#78 New API for clients.
  execution-engine/Cargo.toml
  execution-engine/src/error/common.rs
  execution-engine/src/error/mod.rs
  execution-engine/src/error/wasmi.rs
  execution-engine/src/factory.rs
  execution-engine/src/hcall/buffer.rs
  execution-engine/src/hcall/common.rs
  execution-engine/src/hcall/mod.rs
  execution-engine/src/hcall/wasmi.rs
  execution-engine/src/hcall/wasmtime.rs
  execution-engine/src/lib.rs
  runtime-manager/build.rs
  runtime-manager/src/managers/buffer.rs
  runtime-manager/src/managers/error.rs
  runtime-manager/src/managers/execution_engine_manager.rs
  runtime-manager/src/managers/mod.rs
  runtime-manager/src/managers/session_manager.rs
  runtime-manager/src/runtime_manager_nitro.rs
  runtime-manager/src/runtime_manager_sgx.rs
  runtime-manager/src/runtime_manager_trustzone.rs
  sdk/data-generators/number-stream-generator/src/main.rs
  sdk/freestanding-execution-engine/Cargo.toml
  sdk/freestanding-execution-engine/config/execution-engine.toml
  sdk/freestanding-execution-engine/src/main.rs
  sdk/rust-language-support/examples/number-stream-accumulation/src/main.rs
  session-manager/src/session.rs
  session-manager/src/session_context.rs
  test-collateral/Makefile
  test-collateral/generate-policy/Cargo.toml
  test-collateral/generate-policy/src/main.rs
  transport-protocol/protos/transport_protocol.proto
  transport-protocol/src/custom.rs
  veracruz-client/src/error.rs
  veracruz-client/src/tests.rs
  veracruz-client/src/veracruz_client.rs
  veracruz-server-test/src/main.rs
  veracruz-test/src/main.rs
  veracruz-utils/Cargo.toml
  veracruz-utils/src/io/raw_fd.rs
  veracruz-utils/src/platform/nitro/nitro.rs
  veracruz-utils/src/platform/nitro/nitro_enclave.rs
  veracruz-utils/src/policy/error.rs
  veracruz-utils/src/policy/expiry.rs
  veracruz-utils/src/policy/policy.rs
  veracruz-utils/src/policy/principal.rs
Labels: client-code, enhancement, trusted-veracruz-runtime

#128 Added invitation to weekly Zoom meeting to README
  README.markdown
Labels: documentation, repository

#130 Cutting the apron strings
  .gitlab-ci.yml
  sdk/data-generators/csv-encoder/src/main.rs
  sdk/data-generators/idash2017-logistic-regression-generator/src/main.rs
  sdk/data-generators/intersection-set-sum-generator/src/main.rs
  sdk/data-generators/linear-regression-generator/src/main.rs
  sdk/data-generators/moving-average-convergence-divergence-generator/src/main.rs
  sdk/data-generators/number-stream-generator/src/main.rs
  sdk/data-generators/private-set-intersection-generator/src/main.rs
  sdk/data-generators/private-set-intersection-sum-generator/src/main.rs
  sdk/data-generators/string-generator/src/main.rs
  sgx-root-enclave/Makefile
Labels: build-process, documentation, repository

#129 Changed wording of license file given CCC adoption
  LICENSE.markdown
Labels: documentation, repository

#131 Added link to public Slack channel in README
  README.markdown
Labels: documentation, repository
