Repository veracruz-project/veracruz, pull requests merged in 2021-12, with the labels that each got.

#286 veracruz-utils/src/csr.rs: Generate certificate valid till 2031-02-01.
  veracruz-utils/src/csr.rs
Labels: bug, trusted-veracruz-runtime, build-process, testing, server

#272 Prepare v1.0 release
  .github/workflows/main.yml
  .gitmodules
  execution-engine/Cargo.toml
  io-utils/Cargo.toml
  linux-root-enclave/Cargo.lock
  linux-root-enclave/Cargo.toml
  platform-services/Cargo.toml
  platform-services/Xargo.toml
  policy-utils/Cargo.toml
  proxy-attestation-server/Cargo.lock
  proxy-attestation-server/Cargo.toml
  psa-attestation/Cargo.toml
  psa-attestation/Xargo.toml
  runtime-manager-bind/Cargo.lock.sgx
  runtime-manager/Cargo.lock
  runtime-manager/Cargo.toml
  runtime-manager/Xargo.toml
  sdk/data-generators/idash2017-logistic-regression-generator/Cargo.lock
  sdk/data-generators/image-processing-generator/Cargo.lock
  sdk/data-generators/intersection-set-sum-generator/Cargo.lock
  sdk/data-generators/linear-regression-generator/Cargo.lock
  sdk/data-generators/moving-average-convergence-divergence-generator/Cargo.lock
  sdk/data-generators/number-stream-generator/Cargo.lock
  sdk/data-generators/private-set-intersection-generator/Cargo.lock
  sdk/data-generators/private-set-intersection-sum-generator/Cargo.lock
  sdk/data-generators/shamir-secret-sharing/Cargo.lock
  sdk/data-generators/string-generator/Cargo.lock
  sdk/freestanding-execution-engine/Cargo.lock
  sdk/freestanding-execution-engine/Cargo.toml
  sdk/rust-examples/idash2017-logistic-regression/Cargo.lock
  sdk/rust-examples/image-processing/Cargo.lock
  sdk/rust-examples/intersection-set-sum/Cargo.lock
  sdk/rust-examples/linear-regression/Cargo.lock
  sdk/rust-examples/logistic-regression/Cargo.lock
  sdk/rust-examples/moving-average-convergence-divergence/Cargo.lock
  sdk/rust-examples/nop/Cargo.lock
  sdk/rust-examples/number-stream-accumulation/Cargo.lock
  sdk/rust-examples/private-set-intersection-sum/Cargo.lock
  sdk/rust-examples/private-set-intersection/Cargo.lock
  sdk/rust-examples/random-source/Cargo.lock
  sdk/rust-examples/read-file/Cargo.lock
  sdk/rust-examples/shamir-secret-sharing/Cargo.lock
  sdk/rust-examples/string-edit-distance/Cargo.lock
  session-manager/Cargo.toml
  session-manager/Xargo.toml
  sgx-root-enclave-bind/Cargo.lock
  sgx-root-enclave/Cargo.lock
  sgx-root-enclave/Cargo.toml
  test-collateral/generate-policy/Cargo.lock
  test-collateral/generate-policy/Cargo.toml
  transport-protocol/Cargo.toml
  veracruz-client/Cargo.lock
  veracruz-client/Cargo.toml
  veracruz-server-test/Cargo.lock
  veracruz-server-test/Cargo.toml
  veracruz-server/Cargo.lock
  veracruz-server/Cargo.toml
  veracruz-test/Cargo.lock
  veracruz-test/Cargo.toml
  veracruz-utils/Cargo.toml
Labels: repository, always-refactoring

#296 Update platform information in documentation and error message.
  COMPONENTS.markdown
  platform-services/src/lib.rs
  runtime-manager/src/lib.rs
  runtime-manager/src/main.rs
  runtime-manager/src/runtime_manager.rs
Labels: bug, documentation

#299 Remove redundant ta_static.rs file
  runtime-manager/ta_static.rs
Labels: repository, always-refactoring

#294 Fixed non-expiring Slack invite in README
  README.markdown
Labels: bug, documentation, repository

#301 Run rustfmt over some files.
  execution-engine/src/wasi/common.rs
  execution-engine/src/wasi/wasmi.rs
  execution-engine/src/wasi/wasmtime.rs
  sdk/freestanding-execution-engine/src/main.rs
Labels: enhancement, trusted-veracruz-runtime, always-refactoring

#302 Some post-TrustZone/SGX removal cleanup
  Makefile
  runtime-manager-bind/Cargo.toml
  runtime-manager-bind/build.rs
  runtime-manager-bind/src/lib.rs
  runtime-manager-bind/wrapper.h
  runtime-manager-uuid.txt
  runtime-manager/Cargo.toml
  screenrc
  veracruz-server/Cargo.toml
  veracruz-utils/Cargo.toml
Labels: repository, trusted-veracruz-runtime, build-process, always-refactoring

#252 Applied rustfmt uniformly across codebase
  .github/workflows/main.yml
  Makefile
  execution-engine/src/fs.rs
  io-utils/src/http.rs
  io-utils/src/lib.rs
  proxy-attestation-server/src/attestation/psa.rs
  proxy-attestation-server/src/cli.rs
  proxy-attestation-server/src/error.rs
  proxy-attestation-server/src/orm/mod.rs
  runtime-manager/Makefile
  runtime-manager/src/managers/execution_engine_manager.rs
  runtime-manager/src/managers/mod.rs
  sdk/Makefile
  sdk/data-generators/idash2017-logistic-regression-generator/Makefile
  sdk/data-generators/image-processing-generator/Makefile
  sdk/data-generators/intersection-set-sum-generator/Makefile
  sdk/data-generators/linear-regression-generator/Makefile
  sdk/data-generators/moving-average-convergence-divergence-generator/Makefile
  sdk/data-generators/number-stream-generator/Makefile
  sdk/data-generators/private-set-intersection-generator/Makefile
  sdk/data-generators/private-set-intersection-sum-generator/Makefile
  sdk/data-generators/shamir-secret-sharing/Makefile
  sdk/data-generators/string-generator/Makefile
  sdk/freestanding-execution-engine/Makefile
  sdk/rust-examples/audio-event-triangulation/Makefile
  sdk/rust-examples/idash2017-logistic-regression/Makefile
  sdk/rust-examples/image-processing/Makefile
  sdk/rust-examples/intersection-set-sum/Makefile
  sdk/rust-examples/linear-regression/Makefile
  sdk/rust-examples/logistic-regression/Makefile
  sdk/rust-examples/moving-average-convergence-divergence/Makefile
  sdk/rust-examples/nop/Makefile
  sdk/rust-examples/number-stream-accumulation/Makefile
  sdk/rust-examples/private-set-intersection-sum/Makefile
  sdk/rust-examples/private-set-intersection/Makefile
  sdk/rust-examples/random-source/Makefile
  sdk/rust-examples/read-file/Makefile
  sdk/rust-examples/shamir-secret-sharing/Makefile
  sdk/rust-examples/string-edit-distance/Makefile
  session-manager/src/error.rs
  test-collateral/Makefile
  test-collateral/generate-policy/Makefile
  test-collateral/generate-policy/src/main.rs
  veracruz-client/src/cli.rs
  veracruz-client/src/veracruz_client.rs
  veracruz-mcu-client/Makefile
  veracruz-utils/src/csr.rs
Labels: sdk, trusted-veracruz-runtime, client-code, always-refactoring, server

#310 main: Fix CLI quickstarts
  CLI_INSTRUCTIONS.markdown
  CLI_QUICKSTART.markdown
Labels: bug, documentation

#298 Switch to Veracruz fork of pinecone.
  execution-engine/Cargo.toml
  sdk/data-generators/csv-encoder/Cargo.toml
  sdk/data-generators/idash2017-logistic-regression-generator/Cargo.toml
  sdk/data-generators/intersection-set-sum-generator/Cargo.toml
  sdk/data-generators/linear-regression-generator/Cargo.toml
  sdk/data-generators/moving-average-convergence-divergence-generator/Cargo.toml
  sdk/data-generators/number-stream-generator/Cargo.toml
  sdk/data-generators/private-set-intersection-generator/Cargo.toml
  sdk/data-generators/private-set-intersection-sum-generator/Cargo.toml
  sdk/data-generators/string-generator/Cargo.toml
  sdk/freestanding-execution-engine/Cargo.toml
  sdk/rust-examples/idash2017-logistic-regression/Cargo.toml
  sdk/rust-examples/intersection-set-sum/Cargo.toml
  sdk/rust-examples/linear-regression/Cargo.toml
  sdk/rust-examples/logistic-regression/Cargo.toml
  sdk/rust-examples/moving-average-convergence-divergence/Cargo.toml
  sdk/rust-examples/number-stream-accumulation/Cargo.toml
  sdk/rust-examples/private-set-intersection-sum/Cargo.toml
  sdk/rust-examples/private-set-intersection/Cargo.toml
  sdk/rust-examples/random-source/Cargo.toml
  sdk/rust-examples/read-file/Cargo.toml
  sdk/rust-examples/string-edit-distance/Cargo.toml
  veracruz-server/Cargo.toml
  veracruz-test/Cargo.toml
Labels: sdk, trusted-veracruz-runtime, client-code, testing, always-refactoring, server

#309 v1: Fix CLI quickstarts
  CLI_INSTRUCTIONS.markdown
  CLI_QUICKSTART.markdown
Labels: bug, documentation
