Repository veracruz-project/veracruz, pull requests merged in 2021-09, with the labels that each got.

#207 Pinned Rouille to v3.2.1
  proxy-attestation-server/Cargo.toml
  veracruz-server/Cargo.toml
Labels: bug, build-process

#206 Replaced AWS CI badge in README for Github Actions
  README.markdown
Labels: documentation, repository, build-process

#209 Removed redundant AWS CodeBuild CI configuration files
  buildspec.yml
  sgx_buildspec.yml
  trustzone_buildspec.yml
Labels: build-process

#211 Change script related to `tar` in CI.
  .github/workflows/main.yml
Labels: enhancement, build-process

#212 freestanding-execution-engine: Avoid broken default_value feature.
  sdk/freestanding-execution-engine/src/main.rs
Labels: bug, sdk, always-refactoring

#214 AUTHORS.markdown: Added Edmund.
  AUTHORS.markdown
Labels: documentation

#210 Added pre-commit hook for code formatting checking
  CONTRIBUTING.markdown
  Makefile
  githooks/pre-commit
Labels: enhancement, repository, build-process

#216 generate-policy: Bug fixes in parsing of command line.
  test-collateral/generate-policy/src/main.rs
Labels: bug, sdk, always-refactoring

#213 Add clock-related functions to platform-services, conditionally implement them in WASI ABI
  execution-engine/src/fs.rs
  execution-engine/src/wasi/wasmi.rs
  execution-engine/src/wasi/wasmtime.rs
  platform-services/Cargo.toml
  platform-services/src/lib.rs
  platform-services/src/nitro_platform_services.rs
  platform-services/src/result.rs
  platform-services/src/sgx_platform_services.rs
  platform-services/src/std_platform_services.rs
  platform-services/src/tz_platform_services.rs
  runtime-manager/src/managers/mod.rs
  sdk/freestanding-execution-engine/src/main.rs
  test-collateral/Makefile
  test-collateral/generate-policy/src/main.rs
  veracruz-utils/src/policy/policy.rs
Labels: enhancement, trusted-veracruz-runtime

#218 Force rustfmt to use 2018 Rust edition in pre-commit hook
  githooks/pre-commit
Labels: bug, repository, build-process

#231 Allow path overrides in test crates
  veracruz-server-test/src/main.rs
  veracruz-test/src/main.rs
Labels: testing, always-refactoring

#226 PAS: Removed dependency on policy.json in the Proxy Attestation Server CLI
  GETTING_STARTED_CLI.markdown
  proxy-attestation-server/src/cli.rs
  proxy-attestation-server/src/server.rs
Labels: enhancement, attestation
