Repository veracruz-project/veracruz, pull requests merged in 2022-05, with the labels that each got.

#339 Fix runtime manager's Makefiles across workspaces
  CLI_QUICKSTART.markdown
  workspaces/linux-host/Makefile
  workspaces/linux-runtime/Makefile
  workspaces/nitro-runtime/Makefile
Labels: enhancement, repository, build-process, always-refactoring

#441 veracruz-2205-release-notes: added release notes
  documents/release-notes/VERACRUZ-2205.markdown
Labels: repository

#439 Specify maximum amount of memory available (Nitro)
  CLI_QUICKSTART.markdown
  io-utils/src/nitro.rs
  policy-utils/src/policy.rs
  test-collateral/generate-policy/src/main.rs
  veracruz-server/src/veracruz_server_nitro.rs
  workspaces/shared.mk
Labels: enhancement, trusted-veracruz-runtime, always-refactoring

#419 Add Clippy linting
  veracruz-utils/src/csr.rs
  workspaces/Makefile
  workspaces/icecap-host/Makefile
  workspaces/linux-host/Makefile
  workspaces/linux-runtime/Makefile
  workspaces/nitro-host/Makefile
  workspaces/nitro-runtime/Makefile
Labels: enhancement, build-process, always-refactoring

#373 Remove superfluous dependencies from Proxy Attestation Server
  CLI_QUICKSTART.markdown
  COMPONENTS.markdown
  docker/base/Dockerfile
  proxy-attestation-server/.env
  proxy-attestation-server/Cargo.toml
  proxy-attestation-server/diesel.toml
  proxy-attestation-server/migrations/2020-03-13-164721_create_devices/down.sql
  proxy-attestation-server/migrations/2020-03-13-164721_create_devices/up.sql
  proxy-attestation-server/src/attestation/psa.rs
  proxy-attestation-server/src/cli.rs
  proxy-attestation-server/src/error.rs
  proxy-attestation-server/src/lib.rs
  proxy-attestation-server/src/orm/mod.rs
  proxy-attestation-server/src/orm/models.rs
  proxy-attestation-server/src/orm/schema.rs
  proxy-attestation-server/src/server.rs
  proxy-attestation-server/src/test.rs
  runtime-manager/src/runtime_manager_linux.rs
  test-collateral/populate-test-database.sh
  veracruz-client/src/attestation.rs
  veracruz-client/src/lib.rs
  veracruz-client/src/tests.rs
  veracruz-client/src/veracruz_client.rs
  veracruz-mcu-client/MCU_CLIENT_INSTRUCTIONS.markdown
  veracruz-mcu-client/run_mcu_demo_server.sh
  veracruz-mcu-client/run_mcu_test_server.sh
  veracruz-server-test/migrations/2020-03-13-164721_create_devices/down.sql
  veracruz-server-test/migrations/2020-03-13-164721_create_devices/up.sql
  veracruz-test/.env
  veracruz-test/migrations/2020-03-13-164721_create_devices/down.sql
  veracruz-test/migrations/2020-03-13-164721_create_devices/up.sql
  workspaces/icecap-host/Makefile
  workspaces/linux-host/Cargo.lock
  workspaces/linux-host/Makefile
  workspaces/nitro-host/Cargo.lock
  workspaces/nitro-host/Makefile
  workspaces/shared.mk
Labels: attestation, build-process, always-refactoring

#449 Added recommended citation to README.markdown, other minor changes
  README.markdown
Labels: documentation, repository

#453 Fix Clippy lints: veracruz-server and veracruz-client
  veracruz-client/src/veracruz_client.rs
  veracruz-server/src/server.rs
  veracruz-server/src/veracruz_server.rs
  veracruz-server/src/veracruz_server_icecap.rs
  veracruz-server/src/veracruz_server_linux.rs
  veracruz-server/src/veracruz_server_nitro.rs
  workspaces/icecap-host/Makefile
  workspaces/linux-host/Makefile
Labels: enhancement, client-code, build-process, always-refactoring, server

#456 Fix clippy lints: host workspaces
  io-utils/src/http.rs
  io-utils/src/nitro.rs
  io-utils/src/raw_fd.rs
  io-utils/src/vsocket.rs
  proxy-attestation-server/src/attestation.rs
  proxy-attestation-server/src/attestation/nitro.rs
  proxy-attestation-server/src/attestation/psa.rs
  proxy-attestation-server/src/error.rs
  psa-attestation/build.rs
  transport-protocol/src/custom.rs
  veracruz-utils/src/csr.rs
  veracruz-utils/src/lib.rs
  veracruz-utils/src/sha256.rs
  workspaces/icecap-host/Makefile
  workspaces/linux-host/Makefile
  workspaces/nitro-host/Makefile
Labels: enhancement, build-process, always-refactoring

#455 Update Wasmtime to version 35
  execution-engine/Cargo.toml
  execution-engine/src/fs.rs
  execution-engine/src/wasi/common.rs
  execution-engine/src/wasi/strace.rs
  execution-engine/src/wasi/wasmi.rs
  execution-engine/src/wasi/wasmtime.rs
  workspaces/host/Cargo.lock
  workspaces/icecap-runtime/Cargo.lock
  workspaces/linux-runtime/Cargo.lock
  workspaces/nitro-runtime/Cargo.lock
Labels: enhancement, trusted-veracruz-runtime, build-process, always-refactoring

#459 Default to debug build
  .github/workflows/main.yml
  CLI_QUICKSTART.markdown
  workspaces/common.mk
Labels: enhancement, build-process

#457 Rework on `veracruz-server-test`
  test-collateral/invalid_policy/expired_certificate.json
  test-collateral/invalid_policy/id:000000,sig:04,src:000000,op:flip1,pos:34.json
  test-collateral/invalid_policy/id:000001,sig:04,src:000000,op:flip1,pos:34.json
  test-collateral/invalid_policy/id:000002,sig:04,src:000000,op:flip1,pos:62.json
  test-collateral/invalid_policy/id:000003,sig:04,src:000000,op:flip1,pos:584.json
  test-collateral/invalid_policy/id:000004,sig:04,src:000000,op:flip1,pos:690.json
  test-collateral/invalid_policy/id:000005,sig:04,src:000000,op:flip1,pos:707.json
  test-collateral/invalid_policy/id:000006,sig:04,src:000000,op:flip1,pos:1417.json
  test-collateral/invalid_policy/id:000007,sig:04,src:000000,op:flip1,pos:2623.json
  test-collateral/invalid_policy/id:000008,sig:04,src:000000,op:flip1,pos:2650.json
  test-collateral/invalid_policy/id:000009,sig:04,src:000000,op:flip2,pos:1417.json
  test-collateral/invalid_policy/id:000010,sig:04,src:000000,op:arith8,pos:62,val:-18.json
  test-collateral/invalid_policy/id:000011,sig:04,src:000000,op:arith8,pos:87,val:-17.json
  test-collateral/invalid_policy/id:000012,sig:04,src:000000,op:arith8,pos:790,val:-7.json
  test-collateral/invalid_policy/invalid_day_format_certificate-1.json
  test-collateral/invalid_policy/invalid_day_format_certificate-2.json
  test-collateral/invalid_policy/invalid_hour_format_certificate-1.json
  test-collateral/invalid_policy/invalid_hour_format_certificate-2.json
  test-collateral/invalid_policy/invalid_min_format_certificate-1.json
  test-collateral/invalid_policy/invalid_min_format_certificate-2.json
  test-collateral/invalid_policy/invalid_month_format_certificate-1.json
  test-collateral/invalid_policy/invalid_month_format_certificate-2.json
  test-collateral/invalid_policy/invalid_year_format_certificate.json
  veracruz-server-test/src/main.rs
  workspaces/icecap-host/Makefile
  workspaces/linux-host/Makefile
  workspaces/nitro-host/Makefile
  workspaces/shared.mk
Labels: bug, testing, always-refactoring

#464 Docs improvement
  AUTHORS.markdown
  CLI_QUICKSTART.markdown
  README.markdown
Labels: documentation, enhancement

#465 Improved error msg when a certificate is not found
  test-collateral/generate-policy/src/main.rs
Labels: enhancement, sdk, always-refactoring

#466 Ignore example files
  .gitignore
Labels: repository, build-process, always-refactoring

#467 Make veracruz_server_linux a bit more reliable.
  veracruz-server/Cargo.toml
  veracruz-server/src/veracruz_server_linux.rs
  workspaces/icecap-host/Cargo.lock
  workspaces/linux-host/Cargo.lock
  workspaces/nitro-host/Cargo.lock
Labels: enhancement, always-refactoring, server
