Repository veracruz-project/veracruz, pull requests merged in 2022-01, with the labels that each got.

#326 Remove old files in sysroot-install target of icecap/mk/realm.mk.
  icecap/mk/realm.mk
  icecap/sysroot/workspace/Cargo.lock
Labels: trusted-veracruz-runtime, build-process, always-refactoring

#325 Enable SIMD proposal in wasmtime
  execution-engine/src/wasi/wasmtime.rs
Labels: enhancement, trusted-veracruz-runtime

#327 Minor improvements to IceCap documentation
  icecap/README.md
Labels: documentation, enhancement

#319 Implement "strace" output functions.
  execution-engine/src/wasi/strace.rs
Labels: enhancement, trusted-veracruz-runtime
