Repository veracruz-project/veracruz, pull requests merged in 2022-03, with the labels that each got.

#332 pre-commit: Run rustfmt without "--skip-children --unstable-features".
  githooks/pre-commit
Labels: bug, build-process

#344 Fix standard streams
  execution-engine/src/fs.rs
  policy-utils/src/lib.rs
  policy-utils/src/parsers.rs
  runtime-manager/src/managers/mod.rs
  sdk/freestanding-execution-engine/src/main.rs
  test-collateral/Makefile
Labels: bug, trusted-veracruz-runtime

#354 Remove icecap/targets.nix and icecap/nix/.../*.nix.
  icecap/nix/default.nix
  icecap/nix/env/host.nix
  icecap/nix/env/realm.nix
  icecap/nix/env/sdk-and-test-collateral.nix
  icecap/nix/host/config.nix
  icecap/nix/instance.nix
  icecap/targets.nix
  workspaces/icecap-host/nix/env/realm.nix
  workspaces/icecap-host/nix/instance.nix
  workspaces/icecap-runtime/Makefile
Labels: enhancement, build-process, always-refactoring

#358 Add workspace Cargo.lock files
  .gitignore
  workspaces/applications/Cargo.lock
  workspaces/host/Cargo.lock
  workspaces/icecap-host/Cargo.lock
  workspaces/icecap-runtime/Cargo.lock
  workspaces/linux-host/Cargo.lock
  workspaces/linux-runtime/Cargo.lock
  workspaces/nitro-host/Cargo.lock
  workspaces/nitro-runtime/Cargo.lock
Labels: enhancement, build-process, always-refactoring

#359 Remove some unused imports and dependencies.
  execution-engine/Cargo.toml
  execution-engine/src/fs.rs
  platform-services/Cargo.toml
  policy-utils/src/parsers.rs
  proxy-attestation-server/Cargo.toml
  psa-attestation/Cargo.toml
  runtime-manager/Cargo.toml
  runtime-manager/src/runtime_manager_nitro.rs
  sdk/freestanding-execution-engine/Cargo.toml
  veracruz-client/Cargo.toml
  veracruz-client/src/tests.rs
  veracruz-client/src/veracruz_client.rs
  veracruz-server/Cargo.toml
  veracruz-server/src/veracruz_server_nitro.rs
  workspaces/host/Cargo.lock
  workspaces/icecap-host/Cargo.lock
  workspaces/icecap-runtime/Cargo.lock
  workspaces/linux-host/Cargo.lock
  workspaces/linux-runtime/Cargo.lock
  workspaces/nitro-host/Cargo.lock
  workspaces/nitro-runtime/Cargo.lock
Labels: build-process, always-refactoring

#364 Remove crate_name pragmas from system components
  runtime-manager/src/lib.rs
  runtime-manager/src/main.rs
  transport-protocol/src/lib.rs
Labels: enhancement, build-process, always-refactoring

#267 Add a new "system call" in a namespace parallel to WASI.
  execution-engine/src/fs.rs
  execution-engine/src/wasi/common.rs
  execution-engine/src/wasi/wasmi.rs
  execution-engine/src/wasi/wasmtime.rs
  sdk/c-examples/README.md
  sdk/c-examples/fd_create/prog.c
  sdk/c-examples/fd_create/test.sh
  sdk/rust-examples/fd_create/Cargo.toml
  sdk/rust-examples/fd_create/src/main.rs
  sdk/rust-examples/fd_create/test.sh
  sdk/rust/libveracruz/Cargo.toml
  sdk/rust/libveracruz/src/lib.rs
  veracruz-server-test/src/main.rs
  workspaces/applications/Cargo.toml
  workspaces/shared.mk
Labels: enhancement, sdk, trusted-veracruz-runtime

#366 Replace occurrences of LICENSE.markdown
  icecap/src/rust/icecap-wrapper/src/lib.rs
  io-utils/src/fd.rs
  io-utils/src/http.rs
  io-utils/src/tcp.rs
  platform-services/src/icecap_platform_services.rs
  policy-utils/src/parsers.rs
  proxy-attestation-server/src/cli.rs
  runtime-manager/src/runtime_manager_icecap.rs
  runtime-manager/src/runtime_manager_linux.rs
  sdk/data-generators/shamir-secret-sharing/Makefile
  sdk/data-generators/shamir-secret-sharing/src/main.rs
  veracruz-client/src/cli.rs
  veracruz-mcu-client/base64.c
  veracruz-mcu-client/base64.h
  veracruz-mcu-client/find_memory_breakdown.py
  veracruz-mcu-client/http.c
  veracruz-mcu-client/http.h
  veracruz-mcu-client/policy_to_header.py
  veracruz-mcu-client/samples/audio-event-triangulation/claps_to_header.py
  veracruz-mcu-client/samples/audio-event-triangulation/main.c
  veracruz-mcu-client/samples/shamir-secret-sharing/binary_to_header.py
  veracruz-mcu-client/samples/shamir-secret-sharing/main.c
  veracruz-mcu-client/slip-setup.sh
  veracruz-mcu-client/tap-setup.sh
  veracruz-mcu-client/vc.c
  veracruz-mcu-client/vc.h
  veracruz-mcu-client/xxd.c
  veracruz-mcu-client/xxd.h
  veracruz-server/src/cli.rs
  veracruz-server/src/veracruz_server_icecap.rs
  veracruz-server/src/veracruz_server_linux.rs
  veracruz-utils/src/platform/error.rs
  veracruz-utils/src/platform/icecap/message.rs
  veracruz-utils/src/platform/icecap/mod.rs
  veracruz-utils/src/platform/vm.rs
Labels: enhancement, always-refactoring

#341 Veracruz Server Nitro: Remove 10s sleep after launching the runtime manager
  veracruz-server/src/veracruz_server_nitro.rs
Labels: enhancement, always-refactoring, server

#277 Reduce latency in the network stack
  io-utils/src/http.rs
  proxy-attestation-server/src/attestation.rs
  proxy-attestation-server/src/attestation/nitro.rs
  proxy-attestation-server/src/attestation/psa.rs
  proxy-attestation-server/src/server.rs
  runtime-manager/src/managers/execution_engine_manager.rs
  runtime-manager/src/runtime_manager_linux.rs
  transport-protocol/Cargo.toml
  transport-protocol/src/custom.rs
  veracruz-client/src/veracruz_client.rs
  veracruz-server-test/src/main.rs
  veracruz-server/fuzz/fuzz_targets/provision_data.rs
  veracruz-server/src/veracruz_server_icecap.rs
  veracruz-server/src/veracruz_server_linux.rs
  veracruz-server/src/veracruz_server_nitro.rs
Labels: enhancement, trusted-veracruz-runtime, always-refactoring, server

#372 Add `RUNTIME_ENCLAVE_BINARY_PATH` environment variable
  veracruz-server/src/veracruz_server_linux.rs
  workspaces/linux-host/Makefile
Labels: enhancement

#368 Delayed load of policy in IceCap attestation
  runtime-manager/src/runtime_manager_icecap.rs
  veracruz-server/src/veracruz_server_icecap.rs
  veracruz-utils/src/platform/icecap/message.rs
Labels: trusted-veracruz-runtime, attestation, always-refactoring, server
